name: Publish releases to WinGet
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: BeagleSoftware.BeagleEditor
          version: ${{ github.event.release.tag_name }}
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: ManiArasteh